# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gameboard.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gameboard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgameboard.proto\",\n\x10\x43lientSubscriber\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"9\n\x11SubscribeResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\"\n\x11\x45ventNotification\x12\r\n\x05\x65vent\x18\x01 \x01(\t\" \n\x0eNotifyResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2y\n\x10SubscribeService\x12\x34\n\tSubscribe\x12\x11.ClientSubscriber\x1a\x12.SubscribeResponse\"\x00\x12/\n\x06Notify\x12\x12.EventNotification\x1a\x0f.NotifyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gameboard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTSUBSCRIBER']._serialized_start=19
  _globals['_CLIENTSUBSCRIBER']._serialized_end=63
  _globals['_SUBSCRIBERESPONSE']._serialized_start=65
  _globals['_SUBSCRIBERESPONSE']._serialized_end=122
  _globals['_EVENTNOTIFICATION']._serialized_start=124
  _globals['_EVENTNOTIFICATION']._serialized_end=158
  _globals['_NOTIFYRESPONSE']._serialized_start=160
  _globals['_NOTIFYRESPONSE']._serialized_end=192
  _globals['_SUBSCRIBESERVICE']._serialized_start=194
  _globals['_SUBSCRIBESERVICE']._serialized_end=315
# @@protoc_insertion_point(module_scope)
